//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indstempling
    {
        public int IndstemplingID { get; set; }
        public string TidStatus { get; set; }
        public System.DateTime Tidspunkt { get; set; }
        public int FK_PersonID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
