//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Entities : DbContext
    {
        public DB_Entities()
            : base("name=DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ansat> Ansats { get; set; }
        public virtual DbSet<AnsTovRelation> AnsTovRelations { get; set; }
        public virtual DbSet<Frivillig> Frivilligs { get; set; }
        public virtual DbSet<Indstempling> Indstemplings { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<TovFriRelation> TovFriRelations { get; set; }
        public virtual DbSet<Tovholder> Tovholders { get; set; }
    }
}
