//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Indstemplings = new HashSet<Indstempling>();
        }
    
        public int PersonID { get; set; }
        public string Navn { get; set; }
        public string Efternavn { get; set; }
        public string Tlf { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string QrID { get; set; }
        public int Status { get; set; }

        public virtual Ansat Ansat { get; set; }
        public virtual Frivillig Frivillig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indstempling> Indstemplings { get; set; }
        public virtual Tovholder Tovholder { get; set; }
    }
}
